feat: Add data proxy docs
prisma/docs pull request #2407
Opened 2021-10-19 12:04 UTC by albertoperdomo

This PR adds the data proxy to our Prisma Data Platform docs.

To review:
* Preview deployment is at https://deploy-preview-2407--prisma2-docs.netlify.app/
* Navigate to Concepts -> Components -> Prisma Data Platform

2021-10-19 12:54 UTC, br0kend approved these changes
lgtm

2021-10-19 13:05 UTC, Jolg42 commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +To use the data proxy, you will version `3.3.0` or higher of the `prisma` and `prisma-client` npm packages.
```suggestion
To use the data proxy, you will need the version `3.3.0` or higher of the `prisma` and `@prisma/client` npm packages. 
```

2021-10-19 13:06 UTC, Jolg42 commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +Navigate to the "Data Proxy" tab of your Prisma Cloud project, select desired proxy location, and click on "Enable".
```suggestion
Navigate to the "Data Proxy" tab of your Prisma Cloud project, select the desired proxy location, and click on "Enable".
```

2021-10-19 13:06 UTC, Jolg42 commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +In the generator block of your `Prisma.schema` file, enable the feature flag:
```suggestion
In the generator block of your `schema.prisma` file, enable the feature flag:
```

2021-10-19 13:07 UTC, Jolg42 commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +Currently, the only supported datasource name is `db`. Make sure your `prisma.schema` file includes the `datasource db { ... }` block.
```suggestion
Currently, the only supported datasource name is `db`. Make sure your `schema.prisma` file includes the `datasource db { ... }` block.
```

2021-10-19 13:07 UTC, Jolg42 commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +In the deployment you want to use the proxy, make sure that the `DATABASE_URL` environment variable is set to the proxy connection string.
```suggestion
In the deployment where you want to use the Data Proxy, make sure that the `DATABASE_URL` environment variable is set to the Data Proxy connection string. 
```

2021-10-19 13:08 UTC, Jolg42 commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +We don't know how you run your app, but if you use `env` in your schema, nothing but the value of your environment variable should change. For example:
```suggestion
We don't know how you run your app, but if you use `env()` in your schema, nothing but the value of your environment variable should change. For example:
```

2021-10-19 13:10 UTC, Jolg42 commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +The Data Proxy is architected to seamlessly scale to support large workloads, but during the Early Access period there will be a fairly low scale limit. The actual performance for a single schema usi
```suggestion
The Data Proxy is architected to seamlessly scale to support large workloads, but during the Early Access period there will be a fairly low scale limit. The actual performance for a single schema using the data proxy will depend on a large number of variables (the type of queries, latencies and deployment locations, the performance of your database, ...). The data proxy will not yield more than 200 requests per second. The actual number is hard to predict is likely to be well below.
```

2021-10-19 13:11 UTC, Jolg42 commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +The Data Proxy is provided for free during Early Access. We will use this period to learn about usage and tweak the pricing model. When the Prisma Data Platform is launched in General Availability, t
```suggestion
The Data Proxy is provided for free during Early Access. We will use this period to learn about usage and tweak the pricing model. When the Prisma Data Platform is launched in General Availability, there will an option to use the Data Proxy for free with some limitations, alongside paid options.
```

2021-10-19 13:24 UTC, millsp requested changes

2021-10-19 13:24 UTC, millsp commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +Copy the connection string displayed and store it securely, similarly to how you would treat a database credentials. You may generate more connection strings in this section if you wish and of course
```suggestion
Copy the connection string displayed and store it securely, similarly to how you would treat database credentials. You may generate more connection strings in this section if you wish and of course, revoke them if you don't need them anymore.
```

2021-10-19 13:24 UTC, millsp commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +  previewFeatures = ["dataProxy"]
The casing can be anything, although that is what the engines autocomplete.

2021-10-19 13:24 UTC, millsp commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +In the deployment you want to use the proxy, make sure that the `DATABASE_URL` environment variable is set to the proxy connection string.
```suggestion
In the deployment where you want to use the proxy, make sure that the `DATABASE_URL` environment variable is set to the proxy connection string. 
```

2021-10-19 13:24 UTC, millsp commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +The Data Proxy is architected to seamlessly scale to support large workloads, but during the Early Access period there will be a fairly low scale limit. The actual performance for a single schema usi
```suggestion
The Data Proxy is architected to seamlessly scale to support large workloads, but during the Early Access period there will be a fairly low scale limit. The actual performance for a single schema using the data proxy will depend on a large number of variables (the type of queries, latencies and deployment locations, the performance of your database, ...). The data proxy will not yield more than 200 requests per second. The actual number is hard to predict is likely to be well below.
```

2021-10-19 13:24 UTC, millsp commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +The Data Proxy is provided for free during Early Access. We will use this period to learn about usage and tweak the pricing model. When the Prisma Data Platform is launched in General Availability, t
```suggestion
The Data Proxy is provided for free during Early Access. We will use this period to learn about usage and tweak the pricing model. When the Prisma Data Platform is launched in General Availability, there will be an option to continue using the Data Proxy for free with some limitations, alongside paid options.
```

2021-10-19 13:41 UTC, albertoperdomo commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +Copy the connection string displayed and store it securely, similarly to how you would treat a database credentials. You may generate more connection strings in this section if you wish and of course
it's either singular or plural.

* "a database credential" (without s) or 
* database credentials (in general)

Do you think plural sounds weird? I don't have a strong opinion

2021-10-19 13:42 UTC, albertoperdomo commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +  previewFeatures = ["dataProxy"]
If this is what automcomplete uses, let's stick with this. 😢

2021-10-19 14:27 UTC, millsp commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +Copy the connection string displayed and store it securely, similarly to how you would treat a database credentials. You may generate more connection strings in this section if you wish and of course
I think that both are good

2021-10-19 14:33 UTC, merged

2021-10-19 17:37 UTC, tanberry commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +</Admonition>
@albertoperdomo did you mean to have a question mark at end of the Note?

2021-10-19 18:01 UTC, albertoperdomo commented
No :(

On Tue, 19 Oct 2021 at 18:37, Tana M Berry ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In content/200-concepts/100-components/07-prisma-data-platform.mdx
> <https://github.com/prisma/docs/pull/2407#discussion_r732032728>:
>
> > @@ -39,3 +40,163 @@ In order to add users, you need to use their GitHub username and they need to ha
>  The Prisma Data Platform can have a static IP which you can add to an allowlist in order to connect to your database through our Data Browser.
>
>  You can [create an issue](https://github.com/prisma/studio/issues/new?assignees=&labels=topic%3A+hosted+data+browser&template=hosted-data-browser-bug-report.md&title=) with your request and we will enable it for you. Please note that while this is a feature that will be part of a paid plan in the future, it is currently offered for free while we are in Early Access.
> +
> +## Data Proxy
> +
> +<Admonition type="warning">
> +
> +**Early Access Feature** <br />
> +Please note that the Prisma Data Proxy is an early-stage product and should not be used in production environments?
> +</Admonition>
>
> @albertoperdomo <https://github.com/albertoperdomo> did you mean to have
> a question mark at end of the Note?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/prisma/docs/pull/2407#pullrequestreview-783504240>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAF5GATRXCOWL2U4Z5B67DUHWUE3ANCNFSM5GI7AJJA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-20 09:48 UTC, albertoperdomo commented on content/200-concepts/100-components/07-prisma-data-platform.mdx
> +</Admonition>
No :(
If this is live we should fix it.