Fix cloudflare worker installation
prisma/docs pull request #2419
Opened 2021-10-20 22:15 UTC by matthewmueller

## Describe this PR

This PR incorporates the feedback in https://github.com/prisma/docs/pull/2404 and the edits @tanberry made in https://github.com/prisma/docs/pull/2418.

## Changes

- Fixed missing step about adding webpack
- Fixed typos

2021-10-21 00:03 UTC, ajcwebdev commented
[prisma-mongodb-cloudflare.anthonycampolo.workers.dev](https://prisma-mongodb-cloudflare.anthonycampolo.workers.dev/)

<img width="667" alt="Screen Shot 2021-10-20 at 5 02 33 PM" src="https://user-images.githubusercontent.com/12433465/138188627-9aba81fb-ae0c-4330-b2f6-db1a1add9a22.png">

<img width="946" alt="Screen Shot 2021-10-20 at 5 01 42 PM" src="https://user-images.githubusercontent.com/12433465/138188615-4d4d52d6-9d73-4d85-9d47-ba88785b7eb6.png">

🚀

2021-10-21 01:45 UTC, matthewmueller commented
@ajcwebdev thanks for your help testing this out and reviewing the PR. You're awesome 🙌

2021-10-21 02:24 UTC, ajcwebdev commented
My pleasure @matthewmueller, congratulations on the milestone!

2021-10-21 14:43 UTC, tanberry requested changes
Looks great, only the one little Setup vs Set up... ;-)

2021-10-21 14:43 UTC, tanberry commented on content/300-guides/200-deployment/110-deployment-guides/450-deploying-to-cloudflare-workers.mdx
> +Next, point Wrangler to use this webpack config by adding the following line to your `wrangler.toml`:
Consider this rewrite: "Next, to point Wrangler to use this webpack configuration, add the following line to your `wrangler.toml` file."

(This uses the more imperative and active voice, instead of using "by adding".)

2021-10-21 14:43 UTC, tanberry commented on content/300-guides/200-deployment/110-deployment-guides/450-deploying-to-cloudflare-workers.mdx
> +## 5. Setup Prisma
:-) Set up...

2021-10-22 21:33 UTC, millsp commented
Nice :) I also added an emphasis on the webpack config as one of our users already missed that.

2021-10-25 14:07 UTC, albertoperdomo commented
I am missing a very visible warning callout at the top, about this and the underlying data proxy functionality being in Early Access and not to be used in production.

Like this:

![image](https://user-images.githubusercontent.com/24216/138710738-4e3da38c-3242-44f6-97f7-d1bda32b2515.png)

2021-10-25 14:09 UTC, albertoperdomo requested changes
See https://github.com/prisma/docs/pull/2419#issuecomment-950965676

2021-10-25 14:46 UTC, albertoperdomo commented
Added the warning callout at the top.

2021-10-25 14:46 UTC, albertoperdomo commented
I guess we should close #2418 in favor of this PR?

2021-10-25 15:13 UTC, albertoperdomo approved these changes

2021-10-25 19:32 UTC, tanberry approved these changes

2021-10-25 19:33 UTC, tanberry commented
@matthewmueller shall I go head and merge this or do you want to?

2021-10-25 19:43 UTC, merged

2021-10-25 19:44 UTC, matthewmueller commented
Merged. Thanks everyone!